# Classification of Handwritten Digits using Artificial Neural Networks

## Perform the following steps for above mentioned problem statement:

### 1. Search relevant datasets to perform classification

In [1]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [2]:
print(test_images)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [3]:
print(test_labels)

[7 2 1 ... 4 5 6]


### 2. Classify handwritten digits using a simple neural network that has only input and output layers.

In [4]:
from keras.models import Sequential
from keras.layers import Flatten, Dense
from keras.utils import to_categorical

train_images = train_images.reshape((60000, 28 * 28)).astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28)).astype('float32') / 255
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

model = Sequential()
model.add(Dense(10, activation='softmax', input_shape=(28 * 28,)))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(train_images, train_labels, epochs=5, batch_size=25, validation_split=0.2)
evaluation = model.evaluate(test_images, test_labels)
print(f"Test Accuracy: {evaluation[1]*100:.2f}%")
print(f"Test Loss: {evaluation[0]}")

Epoch 1/5
1920/1920 [==============================] - 5s 2ms/step - loss: 0.4900 - accuracy: 0.8708 - val_loss: 0.3117 - val_accuracy: 0.9136
Epoch 2/5
1920/1920 [==============================] - 4s 2ms/step - loss: 0.3123 - accuracy: 0.9124 - val_loss: 0.2827 - val_accuracy: 0.9218
Epoch 3/5
1920/1920 [==============================] - 4s 2ms/step - loss: 0.2901 - accuracy: 0.9195 - val_loss: 0.2725 - val_accuracy: 0.9252
Epoch 4/5
1920/1920 [==============================] - 4s 2ms/step - loss: 0.2793 - accuracy: 0.9212 - val_loss: 0.2707 - val_accuracy: 0.9251
Epoch 5/5
313/313 [==============================] - 1s 2ms/step - loss: 0.2723 - accuracy: 0.9247
Test Accuracy: 92.47%
Test Loss: 0.27226367592811584


### 3. Add a hidden layer and see how the performance of the model improves.

In [5]:
model = Sequential()
model.add(Dense(100, activation='relu', input_shape=(28 * 28,)))
model.add(Dense(10, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(train_images, train_labels, epochs=5, batch_size=25, validation_split=0.2)
evaluation = model.evaluate(test_images, test_labels)
print(f"Test Accuracy: {evaluation[1]*100:.2f}%")
print(f"Test Loss: {evaluation[0]}")

Epoch 1/5
1920/1920 [==============================] - 6s 3ms/step - loss: 0.2846 - accuracy: 0.9184 - val_loss: 0.1614 - val_accuracy: 0.9546
Epoch 2/5
1920/1920 [==============================] - 5s 3ms/step - loss: 0.1313 - accuracy: 0.9611 - val_loss: 0.1154 - val_accuracy: 0.9662
Epoch 3/5
1920/1920 [==============================] - 5s 3ms/step - loss: 0.0910 - accuracy: 0.9724 - val_loss: 0.1094 - val_accuracy: 0.9664
Epoch 4/5
1920/1920 [==============================] - 5s 3ms/step - loss: 0.0686 - accuracy: 0.9789 - val_loss: 0.0931 - val_accuracy: 0.9728
Epoch 5/5
313/313 [==============================] - 1s 2ms/step - loss: 0.0826 - accuracy: 0.9757
Test Accuracy: 97.57%
Test Loss: 0.08260300010442734


### 4. Apply various activation functions to hidden and output layers to assess the model performance.

In [7]:
activation_functions = ['sigmoid', 'tanh', 'relu']
for activation_function in activation_functions:
    model = Sequential()
    model.add(Dense(100, activation='relu', input_shape=(28 * 28,)))
    model.add(Dense(10, activation= activation_function))
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    model.fit(train_images, train_labels, epochs=5, batch_size=25, validation_split=0.2)
    evaluation = model.evaluate(test_images, test_labels)
    print(f"Test Accuracy with {activation_function}: {evaluation[1]*100:.2f}%")
    print(f"Test Loss with {activation_function}: {evaluation[0]}")

Epoch 1/5
1920/1920 [==============================] - 6s 3ms/step - loss: 0.2807 - accuracy: 0.9194 - val_loss: 0.1541 - val_accuracy: 0.9559
Epoch 2/5
1920/1920 [==============================] - 5s 3ms/step - loss: 0.1243 - accuracy: 0.9641 - val_loss: 0.1128 - val_accuracy: 0.9663
Epoch 3/5
1920/1920 [==============================] - 5s 3ms/step - loss: 0.0871 - accuracy: 0.9737 - val_loss: 0.1082 - val_accuracy: 0.9693
Epoch 4/5
1920/1920 [==============================] - 5s 3ms/step - loss: 0.0666 - accuracy: 0.9796 - val_loss: 0.0977 - val_accuracy: 0.9722
Epoch 5/5
313/313 [==============================] - 1s 2ms/step - loss: 0.0754 - accuracy: 0.9766
Test Accuracy with sigmoid: 97.66%
Test Loss with sigmoid: 0.07542455196380615
Epoch 1/5
1920/1920 [==============================] - 6s 3ms/step - loss: 7.7446 - accuracy: 0.1665 - val_loss: 6.9671 - val_accuracy: 0.1273
Epoch 2/5
1920/1920 [==============================] - 5s 3ms/step - loss: nan - accuracy: 0.1275 - val_los

### 5. Apply various cost functions to measure the error of the model.

In [8]:
loss_functions = ['mean_squared_error', 'categorical_crossentropy', 'binary_crossentropy', 'poisson']
model = Sequential()
model.add(Dense(100, activation='relu', input_shape=(28 * 28,)))
model.add(Dense(10, activation='softmax'))
for loss_function in loss_functions:
    print(f"\nUsing {loss_function} as loss function:")
    model.compile(optimizer='adam', loss=loss_function, metrics=['accuracy'])
    model.fit(train_images, train_labels, epochs=5, batch_size=25, validation_split=0.2)
    evaluation = model.evaluate(test_images, test_labels)
    print(f"Test Accuracy with {loss_function}: {evaluation[1]*100:.2f}%")
    print(f"Test Loss with {loss_function}: {evaluation[0]}")


Using mean_squared_error as loss function:
Epoch 1/5
1920/1920 [==============================] - 6s 3ms/step - loss: 0.0133 - accuracy: 0.9137 - val_loss: 0.0072 - val_accuracy: 0.9558
Epoch 2/5
1920/1920 [==============================] - 5s 3ms/step - loss: 0.0066 - accuracy: 0.9579 - val_loss: 0.0058 - val_accuracy: 0.9645
Epoch 3/5
1920/1920 [==============================] - 5s 3ms/step - loss: 0.0048 - accuracy: 0.9701 - val_loss: 0.0051 - val_accuracy: 0.9667
Epoch 4/5
1920/1920 [==============================] - 5s 3ms/step - loss: 0.0038 - accuracy: 0.9769 - val_loss: 0.0047 - val_accuracy: 0.9694
Epoch 5/5
313/313 [==============================] - 1s 2ms/step - loss: 0.0044 - accuracy: 0.9720
Test Accuracy with mean_squared_error: 97.20%
Test Loss with mean_squared_error: 0.004385668784379959

Using categorical_crossentropy as loss function:
Epoch 1/5
1920/1920 [==============================] - 6s 3ms/step - loss: 0.0668 - accuracy: 0.9844 - val_loss: 0.0942 - val_accurac